[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true      # enable IR-based optimizer pipeline
optimizer = true   # usually keep the optimizer on with via_ir
optimizer_runs = 200

remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "oz-v3/contracts/=lib/oz-v3/contracts/",
  "forge-std-v1.13.0/=lib/forge-std-v1.13.0/src/"
]

[lint]
exclude_lints = [
  "mixed-case-variable",
  "unwrapped-modifier-logic",
  "unchecked-call"
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
